version: '3.7'

services:
  rabbit-mq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    ports: 
      - "${RABBITMQ_FST_PORT}:15672"
      - "${RABBITMQ_SND_PORT}:5672"
    networks:
      - notifier

  couchdb:
    image: couchdb
    ports:
      - "${COUCHDB_PORT}:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    networks:
      - notifier

  app:
    image: app 
    build: 
      context: .
    depends_on:
      - couchdb
      - rabbit-mq
    environment:
      - COUCHDB_PORT=${COUCHDB_PORT} 
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_HOST=couchdb
      - COUCHDB_NAME=${COUCHDB_NAME}
      - RABBITMQ_HOST=rabbit-mq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_EXCHANGE=${RABBITMQ_EXCHANGE}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports: 
      - "${PORT}:4000"
    networks:
      - notifier
networks:
    notifier:
        driver: bridge
        name: notifier